import { describe, it, expect, vi, afterEach } from "vitest";
import {
  detectLang,
  summarySentence,
  runTestsConvention,
  reviewBody,
  refactorBody,
  testingBody,
  unknownRunnerLabel,
  UI,
} from "../src/core/i18n.js";

afterEach(() => vi.restoreAllMocks());

describe("detectLang", () => {
  it("returns es for Spanish locales and en otherwise", () => {
    const spy = vi.spyOn(Intl, "DateTimeFormat");
    spy.mockReturnValue({ resolvedOptions: () => ({ locale: "es-MX" }) } as never);
    expect(detectLang()).toBe("es");
    spy.mockReturnValue({ resolvedOptions: () => ({ locale: "de-DE" }) } as never);
    expect(detectLang()).toBe("en");
    spy.mockImplementation(() => {
      throw new Error("boom");
    });
    expect(detectLang()).toBe("en");
  });
});

describe("shared builders", () => {
  it("builds the summary in both languages", () => {
    expect(summarySentence("es", "Python", "flask")).toBe("Proyecto Python con flask.");
    expect(summarySentence("en", "Python", "flask")).toBe("Python project using flask.");
    expect(summarySentence("es", "Go", "gin", "go modules")).toBe("Proyecto Go con gin (go modules).");
    expect(summarySentence("en", "Go", undefined, "go modules")).toBe("Go project (go modules).");
    expect(summarySentence("es", "Python")).toBe("Proyecto Python.");
  });

  it("builds conventions and prompt bodies in both languages", () => {
    expect(runTestsConvention("es", "pytest")).toBe("Ejecuta los tests con pytest antes de terminar una tarea.");
    expect(runTestsConvention("en", "pytest")).toBe("Run the tests with pytest before finishing a task.");
    expect(reviewBody("en", "incorrect exception handling", "flask")).toContain("incorrect exception handling");
    expect(reviewBody("es", "manejo de excepciones incorrecto", "flask")).toContain("Señala solo problemas concretos");
    expect(reviewBody("es", "", "rails")).toContain("buscando bugs y desviaciones");
    expect(reviewBody("en", "", "rails")).toContain("looking for bugs and deviations");
    expect(refactorBody("en")).toContain("without changing observable behavior");
    expect(testingBody("es", "pytest")).toContain("camino feliz");
    expect(testingBody("en", "pytest")).toContain("happy path");
    expect(unknownRunnerLabel("en")).toBe("the project's test runner");
  });

  it("exposes UI texts for both languages", () => {
    expect(UI.es.sections.commands).toBe("Comandos del repo");
    expect(UI.en.sections.commands).toBe("Repo commands");
    expect(UI.en.generatedHeader).toContain("Generated by agent-rules-init");
    expect(UI.es.question("el framework", "Python")).toContain("¿Cuál usáis?");
    expect(UI.en.question("the framework", "Python")).toContain("Which one do you use?");
    expect(UI.en.fieldLabels.testRunner).toBe("the test runner");
    expect(UI.es.fieldLabels.packageManager).toBe("el gestor de paquetes");
    expect(UI.es.dirNotes.src).toBe("código fuente");
    expect(UI.en.dirNotes.src).toBe("source code");
  });
});
